# Problem 2: Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued term
# a=1
# b=1
# c=2
# d=int(input("Enter the max limit of the fibonacci sequence: "))
# print(a)
# print(b)
# while c<d:    ##This code just prints the fibonacci sequence till less than a desired number
#    print(c)
#    a=b
#    b=c
#    c=a+b
#    continue